---
- name: Ansible Variables
  hosts: external

  environment:
    PLAYBOOK_ENV: "Hello World"

  tasks:
    - name: Use env_var that are playbook and task scoped
      environment:
        TASK_ENV: "FOO BAR"
      ansible.builtin.command: "echo $PLAYBOOK_ENV and $TASK_ENV"

    - name: Ansible builtin variable
      ansible.builtin.debug:
        var: ansible_facts
        # var: playbook_dir
        # var: ansible_version
        # Will playbook_dir and ansible_version work?

